project:
  type: website
  output-dir: docs
  
website:
  title: "Diário de Ecologia de Paisagens"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: exercicio_1.qmd
        text: "1º Exercício"
      - href: exercicio_4.qmd
        text: "4º Exercício"
      - href: exercicio_5.qmd
        text: "5º Exercíco"
      - about.qmd
      
format:
  html:
    theme: minty
    css: styles.css
    toc: true